import Sprockell 

{- This file was automatically generated from a NederScript file.
NederScript is a custom language created by Maarten Meijer and Pepijn Visser 
-} 

prog :: [Instruction] 
prog = [ 
    Branch (1) (Rel (4))
    , Load (ImmValue (1)) (2)
    , Store (2) (DirAddr (0))
    , Jump (Rel (133))
    , ReadInstr (IndAddr (1))
    , Receive (2)
    , Compute (Equal) (2) (0) (3)
    , Branch (3) (Rel (-3))
    , Load (ImmValue (10)) (3)
    , Compute (Add) (2) (3) (3)
    , Jump (Ind (3))
    , Load (ImmValue (0)) (2)
    , Push (2)
    , Pop (2)
    , Store (2) (DirAddr (1))
    , Load (DirAddr (1)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Pop (3)
    , Pop (2)
    , Compute (Lt) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Compute (Sub) (3) (2) (2)
    , Branch (2) (Rel (30))
    , TestAndSet (DirAddr (0))
    , Receive (2)
    , Branch (2) (Rel (2))
    , Jump (Rel (-3))
    , ReadInstr (DirAddr (6))
    , Receive (2)
    , Push (2)
    , Load (ImmValue (20)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Sub) (3) (2) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , WriteInstr (2) (DirAddr (6))
    , WriteInstr (0) (DirAddr (0))
    , Load (DirAddr (1)) (2)
    , Push (2)
    , Load (ImmValue (1)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Add) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (1))
    , Store (2) (DirAddr (1))
    , Jump (Rel (-40))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Sub) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , EndProg
    , Load (ImmValue (0)) (2)
    , Push (2)
    , Pop (2)
    , Store (2) (DirAddr (1))
    , Load (DirAddr (1)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Pop (3)
    , Pop (2)
    , Compute (Lt) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Compute (Sub) (3) (2) (2)
    , Branch (2) (Rel (30))
    , TestAndSet (DirAddr (0))
    , Receive (2)
    , Branch (2) (Rel (2))
    , Jump (Rel (-3))
    , ReadInstr (DirAddr (6))
    , Receive (2)
    , Push (2)
    , Load (ImmValue (20)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Add) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , WriteInstr (2) (DirAddr (6))
    , WriteInstr (0) (DirAddr (0))
    , Load (DirAddr (1)) (2)
    , Push (2)
    , Load (ImmValue (1)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Add) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (1))
    , Store (2) (DirAddr (1))
    , Jump (Rel (-40))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Sub) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , EndProg
    , TestAndSet (DirAddr (0))
    , Receive (2)
    , Branch (2) (Rel (2))
    , Jump (Rel (-3))
    , ReadInstr (DirAddr (6))
    , Receive (2)
    , Push (2)
    , Load (ImmValue (50)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Sub) (3) (2) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , WriteInstr (2) (DirAddr (6))
    , WriteInstr (0) (DirAddr (0))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Sub) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , EndProg
    , Load (ImmValue (0)) (2)
    , Push (2)
    , Pop (2)
    , WriteInstr (2) (DirAddr (6))
    , Load (ImmValue (46)) (2)
    , Push (2)
    , Load (ImmValue (104)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (99)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (103)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (44)) (2)
    , Push (2)
    , Load (ImmValue (121)) (2)
    , Push (2)
    , Load (ImmValue (116)) (2)
    , Push (2)
    , Load (ImmValue (112)) (2)
    , Push (2)
    , Load (ImmValue (109)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (121)) (2)
    , Push (2)
    , Load (ImmValue (108)) (2)
    , Push (2)
    , Load (ImmValue (116)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (117)) (2)
    , Push (2)
    , Load (ImmValue (99)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (116)) (2)
    , Push (2)
    , Load (ImmValue (108)) (2)
    , Push (2)
    , Load (ImmValue (117)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (86)) (2)
    , Push (2)
    , Load (ImmValue (38)) (2)
    , Push (2)
    , Load (ImmValue (83)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (112)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (114)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (111)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (99)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (107)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (101)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (48)) (7)
    , Compute (Add) (7) (1) (7)
    , WriteInstr (7) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (97)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (121)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Jump (Rel (4))
    , Pop (4)
    , WriteInstr (4) (DirAddr (65537))
    , Compute (Sub) (2) (3) (2)
    , Branch (2) (Rel (-3))
    , Load (ImmValue (10)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , ReadInstr (DirAddr (6))
    , Receive (2)
    , Push (2)
    , Load (ImmValue (1000)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Add) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , WriteInstr (2) (DirAddr (6))
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (103)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (98)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (103)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (102)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (84)) (2)
    , Push (2)
    , Load (ImmValue (19)) (2)
    , Push (2)
    , Load (ImmValue (83)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (112)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (114)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (111)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (99)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (107)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (101)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (48)) (7)
    , Compute (Add) (7) (1) (7)
    , WriteInstr (7) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (97)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (121)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Jump (Rel (4))
    , Pop (4)
    , WriteInstr (4) (DirAddr (65537))
    , Compute (Sub) (2) (3) (2)
    , Branch (2) (Rel (-3))
    , Load (ImmValue (10)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Add) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , Load (ImmValue (1)) (2)
    , WriteInstr (2) (DirAddr (1))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Add) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , Load (ImmValue (52)) (2)
    , WriteInstr (2) (DirAddr (2))
    , ReadInstr (DirAddr (5))
    , Receive (3)
    , Load (ImmValue (1)) (4)
    , Compute (Add) (3) (4) (3)
    , WriteInstr (3) (DirAddr (5))
    , Load (ImmValue (103)) (2)
    , WriteInstr (2) (DirAddr (3))
    , ReadInstr (DirAddr (5))
    , Receive (2)
    , Compute (Equal) (2) (0) (3)
    , Load (ImmValue (1)) (4)
    , Compute (Sub) (4) (3) (3)
    , Branch (3) (Rel (-5))
    , Load (ImmValue (58)) (2)
    , Push (2)
    , Load (ImmValue (116)) (2)
    , Push (2)
    , Load (ImmValue (108)) (2)
    , Push (2)
    , Load (ImmValue (117)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (118)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (104)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (99)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (108)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (116)) (2)
    , Push (2)
    , Load (ImmValue (111)) (2)
    , Push (2)
    , Load (ImmValue (84)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (46)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (100)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (104)) (2)
    , Push (2)
    , Load (ImmValue (32)) (2)
    , Push (2)
    , Load (ImmValue (103)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (105)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (101)) (2)
    , Push (2)
    , Load (ImmValue (102)) (2)
    , Push (2)
    , Load (ImmValue (115)) (2)
    , Push (2)
    , Load (ImmValue (110)) (2)
    , Push (2)
    , Load (ImmValue (97)) (2)
    , Push (2)
    , Load (ImmValue (114)) (2)
    , Push (2)
    , Load (ImmValue (84)) (2)
    , Push (2)
    , Load (ImmValue (44)) (2)
    , Push (2)
    , Load (ImmValue (83)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (112)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (114)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (111)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (99)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (107)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (101)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (48)) (7)
    , Compute (Add) (7) (1) (7)
    , WriteInstr (7) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (97)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (121)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Jump (Rel (4))
    , Pop (4)
    , WriteInstr (4) (DirAddr (65537))
    , Compute (Sub) (2) (3) (2)
    , Branch (2) (Rel (-3))
    , Load (ImmValue (10)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , ReadInstr (DirAddr (6))
    , Receive (2)
    , Push (2)
    , Pop (2)
    , WriteInstr (2) (DirAddr (65536))
    , EndProg
    ]

main = run [prog,prog,prog,prog]