import Sprockell 

{- This file was automatically generated from a NederScript file.
NederScript is a custom language created by Maarten Meijer and Pepijn Visser 
-} 

prog :: [Instruction] 
prog = [ 
    Load (ImmValue (1)) (2)
    , Store (2) (DirAddr (0))
    , Load (ImmValue (8)) (2)
    , Push (2)
    , Load (ImmValue (7)) (2)
    , Push (2)
    , Load (ImmValue (6)) (2)
    , Push (2)
    , Load (ImmValue (5)) (2)
    , Push (2)
    , Load (ImmValue (4)) (2)
    , Push (2)
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Compute (Incr) (2) (0) (4)
    , Store (4) (IndAddr (3))
    , Compute (Incr) (3) (0) (3)
    , Jump (Rel (5))
    , Pop (4)
    , Store (4) (IndAddr (3))
    , Compute (Incr) (3) (0) (3)
    , Compute (Decr) (2) (0) (2)
    , Branch (2) (Rel (-4))
    , Load (ImmValue (0)) (2)
    , Push (2)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , Load (DirAddr (6)) (2)
    , Push (2)
    , Load (ImmValue (4)) (2)
    , Push (2)
    , Pop (3)
    , Pop (2)
    , Compute (Lt) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Compute (Sub) (3) (2) (2)
    , Branch (2) (Rel (76))
    , Load (ImmValue (1)) (2)
    , Load (DirAddr (6)) (2)
    , Push (2)
    , Pop (3)
    , Compute (Add) (2) (3) (2)
    , Compute (Incr) (2) (0) (2)
    , Load (IndAddr (2)) (3)
    , Push (3)
    , Load (ImmValue (83)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (112)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (114)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (111)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (99)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (107)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (101)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (108)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (48)) (7)
    , Compute (Add) (7) (1) (7)
    , WriteInstr (7) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (97)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (121)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (115)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (32)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (ImmValue (48)) (7)
    , Load (ImmValue (91)) (6)
    , WriteInstr (6) (DirAddr (65537))
    , Pop (2)
    , Load (ImmValue (1)) (3)
    , Jump (Rel (6))
    , Pop (4)
    , WriteInstr (4) (DirAddr (65536))
    , Load (ImmValue (44)) (6)
    , WriteInstr (6) (DirAddr (65537))
    , Compute (Sub) (2) (3) (2)
    , Compute (Equal) (2) (3) (5)
    , Branch (5) (Rel (3))
    , Branch (2) (Rel (-7))
    , Jump (Rel (3))
    , Pop (4)
    , WriteInstr (4) (DirAddr (65536))
    , Load (ImmValue (93)) (6)
    , WriteInstr (6) (DirAddr (65537))
    , Load (ImmValue (10)) (2)
    , WriteInstr (2) (DirAddr (65537))
    , Load (DirAddr (6)) (2)
    , Push (2)
    , Load (ImmValue (1)) (2)
    , Push (2)
    , Pop (2)
    , Pop (3)
    , Compute (Add) (2) (3) (4)
    , Push (4)
    , Pop (2)
    , Store (2) (DirAddr (6))
    , Jump (Rel (-86))
    , EndProg
    ]

main = run [prog]